name = "BayesianRegressionModels"
uuid = "cdd3e328-398d-47a6-a87b-6047aaf4b4bc"
authors = ["Penelope Yong <penelopeysm@gmail.com>, Peter Thestrup Waade <peter@waade.net>"]
version = "0.1.0"

[deps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
FlexiChains = "4a37a8b9-6e57-4b92-8664-298d46e639f7"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[extensions]
BRMTuringExt = ["Turing", "FlexiChains"]

[compat]
DimensionalData = "0.29"
Distributions = "0.25"
FlexiChains = "0.3"
LinearAlgebra = "1.10"
PDMats = "0.11"
Random = "1.10"
Turing = "0.40"
julia = "1.10"
