[deps]
BayesianRegressionModels = "cdd3e328-398d-47a6-a87b-6047aaf4b4bc"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FlexiChains = "4a37a8b9-6e57-4b92-8664-298d46e639f7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[sources]
BayesianRegressionModels = {path = "../"}
